### ISSUE TITLE
how to use this stuff?

### ISSUE THREAD

**Issue by kostyrev** [emcstack/bonding#1]
I used inventory:

```
cat inventories/bond_test
host20-06fdlne.dc1.xbs.examle.org
host21-06fdlpg.dc1.xbs.examle.org
host22-06fdlph.dc1.xbs.examle.org
host33-06fyceb.dc1.xbs.examle.org
```

with playbook:

```
- hosts: all
  roles:
    - emcstack.bonding
  vars:
  - slaves:
    - eth0
    - eth1
  - bond: bond0
```

invoke ansible-playbook like this:

```
ansible-playbook -i inventories/bond_test -l host20-06fdlne.dc1.xbs.examle.org plays/configure_bond_example.yml --check
```

and it fails with:

```
TASK [emcstack.bonding : Create the slave interfaces configuration files] ******
failed: [host20-06fdlne.dc1.xbs.examle.org] => (item=eth0) => {"failed": true, "item": "eth0", "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVars object' has no attribute u'host20-06fdlne'"}
failed: [host20-06fdlne.dc1.xbs.examle.org] => (item=eth1) => {"failed": true, "item": "eth1", "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVars object' has no attribute u'host20-06fdlne'"}
    to retry, use: --limit @plays/configure_bond_example.retry
```

```
ansible-playbook --version
ansible-playbook 2.0.1.0
```

**Comment by kostyrev** [comment]
Ok, I replaced ansible_hostname with inventory_hostname in
https://github.com/emcstack/bonding/blob/master/templates/rh_ifcfg-slaves.j2#L9

let me see, if I can evetually render configs I want with your role.
If I succeed I'll send a PR

**Comment by JohnPreston** [comment]
Hi Alexandre (if my Russian is not that wrong ^^).
I have just started those little roles and even did changes again today.

I need to come up with a better README for sure, it's a work in progress.

**Comment by kostyrev** [comment]
Yeah, something seriously wrong with the logic in this role.
facts are gathered 4 times:
1. default gather_facts
2. 3 times in rh_ifcfg-slaves.j2

Despite old that, I managed to render what I wanted kinda quickly. This will suffice for me for this moment.

Thank you for effort!

**Comment by JohnPreston** [comment]
Nice stuff. I was adding that kind of logic in the other roles, but definitely have to work more on examples and ease of use.
Thanks :)
